<?php
/**
 * Created by PhpStorm.
 * User: 火子 QQ：284503866.
 * Date: 2020/12/29
 * Time: 14:08
 */

namespace App\Application\Api\Weixin;


use Psr\Http\Message\ResponseInterface as Response;
use Wanphp\Plugins\Weixin\Application\WePublic as WxPublic;

class WePublic extends WxPublic
{
  protected function action(): Response
  {
    return parent::action(); // TODO: Change the autogenerated stub
  }

}
