version: '3.8'

networks:
  backend:
    driver: bridge

# 定义服务nginx,php,mysql,redis
services:
  nginx:
    # 依赖php服务，意味着在启动nginx之前先启动php
    depends_on:
      - php-fpm
    #image: wanphp/nginx
    volumes:
      - ./:/var/www:cached
      - ./var/logs/nginx:/var/log/nginx
      - ./var/conf/nginx/sites:/etc/nginx/sites-available
      - ./var/conf/nginx/ssl:/etc/nginx/ssl
    # nginx意外退出时自动重启
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    # 映射80和443端口
    ports:
      - "80:80"
      - "443:443"
    # 容器名称
    container_name: nginx-slim
    networks:
      - backend

  php-fpm:
    #image: wanphp/php
    build: ./docker/php
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - ./:/var/www:cached
    container_name: php-fpm-slim
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

  mysql:
    #image: wanphp/mysql
    build: ./docker/mysql
    volumes:
      - ./var/data/mysql:/var/lib/mysql
      - ./var/logs/mysql:/var/log/mysql
      - ./var/backup/mysql:/backup
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
      DATABASE_ADMIN_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      DATABASE_RO_PASSWORD: ${DATABASE_RO_PASSWORD}
    #ports:
    #  - "13306:3306"
    container_name: mysql-slim
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis:
    #image: wanphp/redis
    build: ./docker/redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./var/data/redis:/data
    restart: always
    #ports:
    #  - "16379:6379"
    container_name: redis-slim
    networks:
      - backend

  worker:
    #image: wanphp/php_worker:latest
    build: ./docker/worker
    container_name: log-worker
    working_dir: /app
    volumes:
      - ./:/app
    command: php bin/worker.php audit
    restart: always
    depends_on:
      - redis
      - mysql
    networks:
      - backend


  composer:
    image: composer:latest
    command: [ "composer", "update" ]
    container_name: composer-slim
    volumes:
      - ./:/app
