location ^~ /image/ {
    alias $upload_file_path/image/;
    # 只允许图片
    location ~* \.(jpg|jpeg|png|gif|webp)$ {
        expires 365d;
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header X-Content-Type-Options nosniff;
        # 防盗链
        if ($valid_referer_custom = 0) {
            return 404;
        }
        access_log off;
    }

    # 禁止其他文件
    location ~* \.(php|phtml|phar|sh|pl|cgi|exe)$ {
        return 403;
    }
}

location ^~ /image/thumb/ {
    alias $upload_file_path/image/thumb/;
    # WebP 支持判断
    set $webp_suffix "";
    if ($http_accept ~* "webp") {
        set $webp_suffix ".webp";
    }
    location ~* \.(jpg|jpeg|png|gif|webp)$ {
        try_files $uri$webp_suffix $uri /index.php$is_args$args;
        expires 365d;
        add_header Cache-Control "public, max-age=31536000, immutable";
        add_header Vary Accept always;
        add_header X-Content-Type-Options nosniff;

        access_log off;
    }
}

location ^~ /video/ {
    alias $upload_file_path/video/;
    types {
        video/mp4 mp4;
        video/webm webm;
    }

    expires 30d;
    add_header Cache-Control "public";

    # 支持断点续传
    add_header Accept-Ranges bytes;

    access_log off;
}

location ^~ /audio/ {
    alias $upload_file_path/audio/;
    types {
        audio/mpeg mp3;
        audio/ogg ogg;
    }

    expires 30d;
    add_header Cache-Control "public";

    access_log off;
}

# 文件（只能下载）
location /protected-files/ {
  internal;
  alias $upload_file_path/;
}
# 禁止上传目录执行脚本
location ~* ^/(image|video|audio|protected-files)/.*\.(php|phtml|phar|sh|pl|cgi|exe)$ {
    return 403;
}
