# 只允许访问图片文件
location ~* ^/image/(?!thumb/).+\.(jpg|png|gif|webp)$ {
  root $wwwroot/var/uploadFiles;
  expires 365d;
  add_header Cache-Control "public, max-age=31536000";
  add_header X-Content-Type-Options nosniff;
  #valid_referers none blocked wanphp.com;
  #if ($invalid_referer) {
  #  return 404;
  #}
  access_log off;
}

location ~* ^(?<img>/image/thumb/.+)\.(?<ext>jpg|png|gif|webp)$ {
  root $wwwroot/var/uploadFiles;
  try_files $img.webp $img.$ext /index.php$is_args$args;
  expires 365d;
  add_header Cache-Control "public, max-age=31536000";
  add_header Vary Accept always;
  add_header X-Content-Type-Options nosniff;
  access_log off;
}

location ^~ /video/ {
  alias $wwwroot/var/uploadFiles/video/;
}

location ^~ /audio/ {
  alias $wwwroot/var/uploadFiles/audio/;
}

# images 目录下其它文件一律拒绝
#location /image/ {
#  return 403;
#}
# 文件（只能下载）
location /protected-files/ {
  internal;
  alias $wwwroot/var/uploadFiles/;
}
# 禁止上传目录执行脚本
location ~* ^/(image|protected-files)/.*\.(php|phtml|phar|sh|pl|cgi|exe)$ {
  return 403;
}
