# 反代取微信公众号图片
location ~ /mmbiz_(.*)/ {
  proxy_pass         https://mmbiz.qpic.cn;
  proxy_set_header   Host             "mmbiz.qpic.cn";
  proxy_set_header   Referer          "";
  expires 365d;
  valid_referers none blocked *.wanphp.com;
  if ($invalid_referer) {
    return 404;
  }
}
location ~ /mmbiz/ {
  proxy_pass         https://mmbiz.qpic.cn;
  proxy_set_header   Host             "mmbiz.qpic.cn";
  proxy_set_header   Referer          "";
  expires 365d;
  valid_referers none blocked *.wanphp.com;
  if ($invalid_referer) {
    return 404;
  }
}
location ~ /(.*)_mmbiz_(.*)/ {
  proxy_pass         https://mmbiz.qpic.cn;
  proxy_set_header   Host             "mmbiz.qpic.cn";
  proxy_set_header   Referer          "";
  expires 365d;
  valid_referers none blocked *.wanphp.com;
  if ($invalid_referer) {
    return 404;
  }
}
location ~ /mmopen/ {
  proxy_pass         https://wx.qlogo.cn;
  proxy_set_header   Host             "wx.qlogo.cn";
  proxy_set_header   Referer          "";
  expires 365d;
  valid_referers none blocked *.wanphp.com;
  if ($invalid_referer) {
    return 404;
  }
}
