server {

  listen 443 ssl;
  listen [::]:443 ssl;

  include sites-available/common/ssl.conf;
  include sites-available/common/security.conf;

  set $wwwroot /var/www;
  server_name wanphp.com www.wanphp.com;
  root /var/www/public;
  index index.php index.html;

  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  include sites-available/common/php-fpm.conf;
  include sites-available/common/upfiles.conf;
  include sites-available/common/wximage.conf;

  location ~ /\.ht {
    deny all;
  }

  error_log /var/log/nginx/default_error.log;
  access_log /var/log/nginx/default_access.log;
}
